---
exclude_paths:
  - "Highlight.Api/bin/**"
  - "Highlight.Api/obj/**"
  - "Highlight.Api.Test/bin/**"
  - "Highlight.Api.Test/obj/**"
engines:
  sonarcsharp:
    exclude_paths:
      - "Highlight.Api/Interfaces/**"
